version: "3.9"

services:
  goldframe:
    image: ghcr.io/bartoszciszek/goldframe:prod
    container_name: goldframe
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
